
import pytest
import io
import pandas as pd
from rosetta.sniffer import sniff_header_row
from rosetta.logic.sniffer_logic import calculate_data_density, detect_header_by_density

def test_data_density_calculation():
    # Helper test to verify density logic
    assert calculate_data_density("12.50;2023-01-01;Description") > 0.5
    assert calculate_data_density("Header;Date;Amount") < 0.2

def test_detect_header_by_density_simple():
    lines = [
        "Company Metadata",
        "Export Date: 2023",
        "Date,Amount,Desc",
        "2023-01-01,100,Test",
        "2023-01-02,200,Test2"
    ]
    # Header is at index 2
    # Data starts at index 3
    # Logic: First Data Row is 3. Preceding is 2.
    assert detect_header_by_density(lines) == 2

def test_detect_header_by_keywords_fallback():
    # If density fails (e.g. data looks like text or empty)
    # We construct a case where density is low but keywords match
    lines = [
        "Garbage",
        "Date;Amount;Description", # High keyword score
        "Jan;One;Test",            # Low data density (words instead of numbers)
        "Feb;Two;Test"
    ]
    # detect_header_by_density might fail or return None if data density is low.
    # But sniff_header_row should pick it up via fallback.
    df = sniff_header_row(io.StringIO("\n".join(lines)))
    assert "Date" in df.columns
    assert "Amount" in df.columns

def test_sniff_header_standard_csv():
    csv_content = """Date,Amount,Description
2023-01-01,100.50,Payment
2023-01-02,25.00,Groceries
"""
    df = sniff_header_row(io.StringIO(csv_content))
    assert len(df) == 2
    assert "Date" in df.columns

def test_sniff_header_with_metadata():
    csv_content = """Report Generated by Bank
Account: 123456
----------------
Date;Amount;Valuta
2023-01-01;100,50;EUR
2023-01-02;200,00;EUR
"""
    df = sniff_header_row(io.StringIO(csv_content))
    assert "Valuta" in df.columns
    assert len(df) == 2

def test_empty_content():
    df = sniff_header_row(io.StringIO(""))
    assert df.empty

def test_sniff_header_real_world_dutch_masked():
    # Extracted from short_XLS241110153954.xls (Masked)
    # Row 0 is header.
    csv_content = """Rekeningnummer;Muntsoort;Transactiedatum;Rentedatum;Beginsaldo;Eindsaldo;Transactiebedrag;Omschrijving
546789123;EUR;20240831;20240831;6082.44;6077.44;-5;Payment Description 1
546789123;EUR;20240901;20240901;6077.44;6071.49;-5.95;Payment Description 2
"""
    df = sniff_header_row(io.StringIO(csv_content))
    assert "Rekeningnummer" in df.columns
    assert "Transactiebedrag" in df.columns
    assert len(df) == 2

def test_sniff_header_german():
    # German sample: "Datum", "Betrag", "Verwendungszweck"
    csv_content = """Kontoauszug 2023
Kunde: Hans Muller
Datum;Betrag;Waehrung;Verwendungszweck
01.01.2023;-50,00;EUR;Miete
02.01.2023;2000,00;EUR;Gehalt
"""
    df = sniff_header_row(io.StringIO(csv_content))
    assert "Datum" in df.columns
    assert "Verwendungszweck" in df.columns
    assert len(df) == 2

def test_sniff_header_spanish():
    # Spanish sample: "Fecha", "Importe", "Concepto"
    csv_content = """Extracto Bancario
Banco de Espana
Fecha,Importe,Saldo,Concepto
2023-01-01,-100.50,5000.00,Compra Supermercado
2023-01-02,-20.00,4980.00,Gasolinera
"""
    df = sniff_header_row(io.StringIO(csv_content))
    assert "Fecha" in df.columns
    assert "Concepto" in df.columns
    assert len(df) == 2

def test_sniff_header_long_file():
    # Generate a larger file (50+ lines) where header is at line 10
    header_idx = 10
    lines = [f"Metadata Line {i}" for i in range(header_idx)]
    lines.append("Date,Amount,Description")
    for i in range(50):
        lines.append(f"2023-01-{i%30+1:02d},100.{i},Txn {i}")
        
    csv_content = "\n".join(lines)
    df = sniff_header_row(io.StringIO(csv_content))
def test_sniff_header_long_file_with_errors():
    # Scenario: Header at line 5
    # Some rows have missing columns or extra delimiters (errors)
    # Total rows: ~25
    
    lines = [
        "Bank Export System V2",
        "User: Ashwin",
        "Generated: 2023-10-27",
        "---------------------", # Separator line
        "Date,Amount,Description,Category", # Header (Line 4, index 4)
        "2023-01-01,100.00,Opening Balance,Init",
        "2023-01-02,-50.00,Groceries,Food",
        "2023-01-03,-20.00,Transport,Commute",
        "ERROR_ROW_NO_DELIMITERS", # Should be ignored or handled gracefully by density check
        "2023-01-04,-15.50,Lunch,Food",
        "2023-01-05,,Missing Amount,Unknown", # Missing value
        "2023-01-06,-100.00,Dinner,Food,EXTRA_COL", # Extra column
    ]
    
    # Add filler rows to make it "longer"
    for i in range(7, 25):
        lines.append(f"2023-01-{i%30+1:02d},{-10*i}.00,Item {i},Misc")
        
    csv_content = "\n".join(lines)
    df = sniff_header_row(io.StringIO(csv_content))
    
    # Header detection should still work
    assert "Date" in df.columns
    assert "Category" in df.columns
    # Check that we parsed roughly the right amount of data 
    # (Pandas read_csv with error_bad_lines defaults might skip or warn, but here we just want to ensure header was found)
    assert not df.empty
    # The error row might cause a parse error or be skipped depending on engine='python'
    # We just want to ensure sniff_header_row returned the dataframe starting from the correct header.
    assert df.columns[0] == "Date"

def test_sniff_header_creative_emojis():
    # Scenario: Modern app export with Emojis in header
    # "📅 Date", "💰 Amount", "📝 Desc"
    csv_content = """APP EXPORT v1.0
    
📅 Date;💰 Amount;📝 Desc
2023-01-01;-50.00;Lunch
2023-01-02;-20.00;Taxi
"""
    df = sniff_header_row(io.StringIO(csv_content))
    assert "📅 Date" in df.columns
    assert "💰 Amount" in df.columns
    assert len(df) == 2

def test_sniff_header_creative_quoted_delimiters():
    # Scenario: Headers and data contain delimiters inside quotes
    # Heuristic usually counts delimiters. Does it get confused?
    # "Date, Time", "Amount"
    csv_content = """Report
"Date, Time","Amount","Description, Detailed"
"2023-01-01, 12:00","100.00","Payment, handled"
"2023-01-02, 14:00","50.00","Refund, processed"
"""
    df = sniff_header_row(io.StringIO(csv_content))
    assert "Date, Time" in df.columns
    assert len(df) == 2

def test_sniff_header_creative_json_blobs():
    # Scenario: A column contains JSON blobs which have many symbols/digits
    # This checks if the density heuristic falsely flags a metadata row if it was dense
    # But here we show it correctly finding the transition to tabular data.
    
    # Metadata is sparse
    lines = ["System: Core", "User: Admin", "----------------"]
    # Header
    lines.append("ID;JSON_Content;Timestamp")
    # Data - High density due to JSON syntax characters {},:
    lines.append("1;{'attr': 123, 'val': 'txt'};2023-01-01")
    lines.append("2;{'attr': 456, 'val': 'num'};2023-01-02")
    
    csv_content = "\n".join(lines)
    df = sniff_header_row(io.StringIO(csv_content))
    assert "JSON_Content" in df.columns
    assert len(df) == 2

def test_sniff_header_edge_window_boundary():
    # SNIFF_WINDOW_SIZE is 20.
    # Scenario: Header is exactly at index 18, Data at index 19 (last checked line).
    # This checks if the scan window covers the last item correctly.
    
    # Lines 0-17: Metadata
    lines = [f"Metadata {i}" for i in range(18)]
    # Line 18: Header
    lines.append("Date,Amount,Description")
    # Line 19: Data (Must satisfy density check to trigger transition)
    # "1,2,3" -> Digits=3, Sep=2. Len=5. Ratio = 1.0. Length > 5 check requires strict > 5...
    # Let's make it clearly data: "2023-01-01,100" -> Digits=8, Sep=3, Total=14 -> Density > 0.5
    lines.append("2023-01-01,100") 
    
    # Total lines 20.
    csv_content = "\n".join(lines)
    df = sniff_header_row(io.StringIO(csv_content))
    # It should find header at 18
    assert "Date" in df.columns
    assert "Amount" in df.columns

def test_sniff_header_threshold_boundary():
    # DATA_DENSITY_THRESHOLD is 0.5
    # We want to test a row that is close to the boundary.
    
    # Case 1: Below threshold (Metadata)
    # "1abcde" -> 1 digit, 6 chars (single col fallback) = 0.16 < 0.5
    
    # Case 2: Above/At threshold (Data)
    # "1,2" -> Tokens: "1" (Num), "2" (Num). Score 1.0 > 0.5
    # "1,a" -> Tokens: "1" (Num), "a" (Text). Score 0.5 >= 0.5
    
    lines = [
        "Metadata line",
        "Header_Col1,Header_Col2",
        "1,value" # Token score 0.5. (Data). Header is prev line. Len > 5.
    ]
    
    csv_content = "\n".join(lines)
    df = sniff_header_row(io.StringIO(csv_content))
    assert "Header_Col1" in df.columns

    lines2 = [
        "Meta",
        "Header_Correct,Col2",
        "1abcde,val", # Density: "1abcde"(0 Num), "val"(0 Num) -> 0.0. (Low). Should be skipped/treated as meta.
        "1,value_long" # "1"(Num), "value_long"(Text) -> 0.5. (High). Data starts here. Len > 5.
    ]
    
    df2 = sniff_header_row(io.StringIO("\n".join(lines2)))
    # "1,value_long" is data (idx 3).
    # Header candidate is idx 2 ("1abcde,val").
    assert "1abcde" in df2.columns

def test_sniff_header_long_description():
    # Scenario: User asked "Will it work if description has really long line of alpha chars?"
    # The Token Density heuristic counts tokens, not characters.
    # So 1 very long text token counts as just 1 non-numeric token.
    # If we have Date(Num), Amount(Num), Desc(Text), Category(Text).
    # 2 Num / 4 Total = 0.5. >= Threshold 0.5. Should pass.
    
    long_text = "A" * 200 # 200 character string
    lines = [
        "Bank Export",
        "Date,Amount,Description,Category",
        f"2023-01-01,100.00,{long_text},Groceries"
    ]
    
    csv_content = "\n".join(lines)
    df = sniff_header_row(io.StringIO(csv_content))
    assert "Date" in df.columns
    assert "Category" in df.columns
    assert len(df) == 1
